# Generated by Django 5.2.5 on 2025-08-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticlepage',
            name='source_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
