# Generated by Django 5.2.5 on 2025-08-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticlepage_source_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name for the source, e.g., 'BBC Technology'", max_length=255)),
                ('url_to_scrape', models.URLField(help_text='The URL of the page that lists the articles.', verbose_name='URL to Scrape')),
                ('base_url', models.URLField(help_text="The base URL used to resolve relative links (e.g., 'https://www.bbc.com').", verbose_name='Base URL')),
                ('html_selector', models.CharField(help_text="The CSS selector for the main content area (e.g., 'main#main-content').", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to temporarily disable scraping for this source.')),
            ],
            options={
                'verbose_name': 'Scraping Source',
                'verbose_name_plural': 'Scraping Sources',
            },
        ),
    ]
